/**
 * Export prompt in multiple formats: TXT, Markdown, JSON
 */

import { downloadTxt } from './downloadTxt';

/**
 * Download prompt as Markdown
 */
export function downloadMarkdown(prompt, filename = 'tiktok-prompt') {
    const md = `# TikTok Affiliate Prompt\n\n> Generated by TikTok Affiliate Prompt Studio\n> Date: ${new Date().toLocaleDateString('id-ID')}\n\n---\n\n${prompt}\n`;
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Parse prompt into JSON structure for integration with other AI tools
 */
export function promptToJSON(prompt, preset, options, meta = {}) {
    const sceneRegex = /(?:SCENE|ADEGAN)\s*(\d+)\s*[:.-]\s*([^\n]+)/gi;
    const matches = [...prompt.matchAll(sceneRegex)];

    const scenes = matches.map((match, i) => {
        const start = match.index;
        const end = i + 1 < matches.length ? matches[i + 1].index : prompt.length;
        const content = prompt.slice(start, end).trim();

        // Extract fields from scene content
        const negMatch = content.match(/Negative Prompt:\s*([^\n]+(?:\n(?!SCENE|ADEGAN|Duration|Prompt|Color|Dialogue|Voiceover|Lip-sync)[^\n]+)*)/i);
        const dialogueMatch = content.match(/(?:Dialogue|Voiceover|Lip-sync):\s*"?([^"\n]+)"?/i);
        const durationMatch = content.match(/Duration:\s*([^\n|]+)/i);
        const beatsMatch = content.match(/Beats:\s*(\d+)/i);
        const cameraMatch = content.match(/Camera:\s*([^\n|]+)/i);
        const moveMatch = content.match(/Move:\s*([^\n]+)/i);
        const promptMatch = content.match(/Prompt:\s*([\s\S]*?)(?=\n(?:Negative Prompt|Dialogue|Voiceover|Lip-sync|Color Grade|SCENE|ADEGAN)|$)/i);
        const colorGradeMatch = content.match(/Color Grade:\s*([^\n]+)/i);

        return {
            scene: parseInt(match[1]),
            title: match[2].trim(),
            duration: durationMatch ? durationMatch[1].trim() : null,
            beats: beatsMatch ? parseInt(beatsMatch[1]) : null,
            camera: cameraMatch ? cameraMatch[1].trim() : null,
            move: moveMatch ? moveMatch[1].trim() : null,
            prompt: promptMatch ? promptMatch[1].trim() : null,
            negativePrompt: negMatch ? negMatch[1].trim() : null,
            dialogue: dialogueMatch ? dialogueMatch[1].trim() : null,
            colorGrade: colorGradeMatch ? colorGradeMatch[1].trim() : null,
            fullContent: content,
        };
    });

    return {
        generator: 'TikTok Affiliate Prompt Studio',
        version: '2.2',
        generatedAt: new Date().toISOString(),
        preset: preset ? {
            id: preset.id,
            name: preset.name,
            category: preset.category,
            vibe: preset.vibe,
            bpmRange: preset.bpmRange,
            energyLevel: preset.energyLevel,
            beatStructure: preset.beatStructure || null,
            transitionStyle: preset.transitionStyle || null,
            wardrobe: preset.wardrobe || null,
            moodKeywords: preset.moodKeywords || [],
        } : null,
        generation: options ? {
            cameraDistance: options.cameraDistance || null,
            lighting: options.lighting || null,
            aspectRatio: options.aspectRatio || null,
            realismLevel: options.realismLevel || null,
            background: options.background || null,
            sceneCount: options.sceneCount || null,
            voiceStyle: options.voiceStyle || null,
        } : null,
        quality: meta?.quality || null,
        sceneCount: scenes.length,
        scenes,
        rawPrompt: prompt,
    };
}

/**
 * Download prompt as structured JSON
 */
export function downloadJSON(prompt, preset, options, filename = 'tiktok-prompt', meta = {}) {
    const data = promptToJSON(prompt, preset, options, meta);
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

export { downloadTxt };
